version: "3"
services:
          prometheus_node_exporter:
                  image: prom/node-exporter
                  hostname: node_exporter
                  container_name: prometheus_node_exporter
                  ports:
                          - "9100:9100"
                  volumes:
                          - "/proc:/host/proc"
                          - "/sys:/host/sys"
                          - "/:/host/rootfs"
                  #entrypoint: "/bin/node_exporter --path.procfs='/host/proc' --path.sysfs='/host/sys' --path.rootfs='/host/rootfs'"
                  command: "--path.procfs='/host/proc' --path.sysfs='/host/sys' --path.rootfs='/host/rootfs'"

          prometheus_process_exporter:
                  image: ncabatoff/process-exporter
                  hostname: process_exporter
                  container_name: prometheus_process_exporter
                  ports:
                          - "9256:9256"
                  volumes:
                          - "/proc:/host/proc"
                          - "./process_exporter_config:/config"
                  command: "--procfs /host/proc --config.path /config/process_list.yml"

          prometheus_rabbitmq_exporter:
                  image: kbudde/rabbitmq-exporter
                  hostname: rabbitmq_exporter
                  container_name: prometheus_rabbitmq_exporter
                  network_mode: "host"
                  ports:
                          - "9419:9419"
                  environment:
                          - "RABBIT_CAPABILITIES=bert,no_sort"
                          - "PUBLISH_PORT=9419"
          prometheus_citaMonitorAgent_port1337_exporter:
                  image: blankwu/cita_agent_by:cita-cli
                  hostname: citaMonitorAgent_port1337_exporter
                  container_name: prometheus_citaMonitorAgent_port1337_exporter
                  pid: "host"
                  ports:
                          - "1920:1920"
                  environment:
                          - "Node=192.168.2.123:1337"
                          - "OpenPort=1920"
