{
 "title": "新监控测试",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ChainHash",
    "label": "ChainHash",
    "query": "ChainInfo_FirstBlocknumber_timestamp{job=\"CITA_ChainInfo\"}"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "ChainInfo_FirstBlocknumber_timestamp{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\"}"
   },
   {
    "name": "chainName",
    "label": "chainName",
    "query": "ChainInfo_ChainMetaData_simple{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\"}"
   },
   {
    "name": "operator",
    "label": "operator",
    "query": "ChainInfo_ChainMetaData_simple{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\"}"
   },
   {
    "name": "tokenname",
    "label": "tokenName",
    "query": "ChainInfo_ChainMetaData_simple{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\"}"
   },
   {
    "name": "tokenSymbol",
    "label": "tokenSymbol",
    "query": "ChainInfo_ChainMetaData_simple{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\"}"
   },
   {
    "name": "economicalModel",
    "label": "economicalModel",
    "query": "ChainInfo_ChainMetaData_timestamp{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\"}"
   },
   {
    "name": "validators",
    "label": "validators",
    "query": "ChainInfo_ChainMetaData_timestamp{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\"}"
   },
   {
    "name": "hostNation",
    "label": "hostNation",
    "query": "ChainInfo_InstanceLocation{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\",instance=\"$instance\"}"
   },
   {
    "name": "hostProvince",
    "label": "hostProvince",
    "query": "ChainInfo_InstanceLocation{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\",instance=\"$instance\"}"
   },
   {
    "name": "hostCity",
    "label": "hostCity",
    "query": "ChainInfo_InstanceLocation{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\",instance=\"$instance\"}"
   },
   {
    "name": "NodeIp",
    "label": "NodeIp",
    "query": "ChainInfo_FirstBlocknumber_timestamp{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\",instance=\"$instance\"}"
   },
   {
    "name": "NodePort",
    "label": "NodePort",
    "query": "ChainInfo_FirstBlocknumber_timestamp{job=\"CITA_ChainInfo\",FirstBlocknumberHash=\"$ChainHash\",instance=\"$instance\"}"
   },
   {
    "name": "NodeInfo_instance",
    "label": "NodeInfo_instance",
    "query": "NodeInfo_LastBlocknumber{NodeIp=\"$NodeIp\",NodePort=\"$NodePort\",job=\"CITA_NodeInfo\"}\t"
   },
   {
    "name": "HostInfo_instance",
    "label": "HostInfo_instance",
    "query": "HostInfo_CPU{NodeIp=\"$NodeIp\",NodePort=\"$NodePort\",job=\"CITA_HostInfo\"}\t"
   }
  ]
 },
 "panels": [
  { "title": "Chain Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "content": "<center>\n<div>\n\n<h1> Chain Name </h1>\n<br>\n<h1 style=\"color:red;\"> $chainName </h1>\n\n</div>\n</center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 1 },
   "content": "<center>\n<div>\n\n<h1> Token Name </h1>\n<br>\n<h1 style=\"color:red;\"> $tokenname </h1>\n\n</div>\n</center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "content": "<center>\n<div>\n\n<h1> Chain Validators </h1>\n<br>\n<h1 style=\"color:red;\"> $validators </h1>\n\n</div>\n</center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "content": "<center>\n<div>\n\n<h1> Operator </h1>\n<br>\n<h1 style=\"color:red;\"> $operator </h1>\n\n</div>\n</center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "content": "<center>\n<div>\n\n<h1> Token Symbol </h1>\n<br>\n<h1 style=\"color:red;\"> $tokenSymbol </h1>\n\n</div>\n</center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 5 },
   "content": "<center>\n<div>\n\n<h1> Chain EconomicalModel </h1>\n<br>\n<h1 style=\"color:red;\"> $economicalModel </h1>\n\n</div>\n</center>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "ChainInfo_ChainMetaData_timestamp{FirstBlocknumberHash=\"$ChainHash\",instance=\"$instance\",job=\"CITA_ChainInfo\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "format": "clockms",
   "valueName": "current",
   "targets": [
    {
     "expr": "ChainInfo_ChainMetaData_timestamp{FirstBlocknumberHash=\"$ChainHash\",instance=\"$instance\",job=\"CITA_ChainInfo\"}"
    }
   ]
  },
  {
   "title": "Running Nodes Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 14 },
   "valueName": "total",
   "targets": [
    {
     "expr": "ChainInfo_InstanceLocation{FirstBlocknumberHash=\"$ChainHash\",job=\"CITA_ChainInfo\"}"
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "NodeInfo_LastBlocknumber{job=\"CITA_NodeInfo\",instance=\"$NodeInfo_instance\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 34 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "NodeInfo_LastBlocknumber_timestamp{job=\"CITA_NodeInfo\",instance=\"$NodeInfo_instance\"}"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 9, "x": 15, "y": 34 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "NodeInfo_NodePeerCounts_full{job=\"CITA_NodeInfo\",instance=\"$NodeInfo_instance\"}"
    }
   ]
  },
  { "title": "Host Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "HostInfo_CPU{instance=\"$HostInfo_instance\",job=\"CITA_HostInfo\"}\t",
     "legendFormat": "{{instance}} CPU use percent"
    }
   ]
  },
  {
   "title": "CPU use by Process",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "HostInfo_CPU_process{instance=\"$HostInfo_instance\",job=\"CITA_HostInfo\"}\t",
     "legendFormat": "{{processName}}"
    }
   ]
  },
  {
   "title": "Momory use by Process",
   "type": "graph",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "HostInfo_Memory_process{instance=\"$HostInfo_instance\",job=\"CITA_HostInfo\"}\t",
     "legendFormat": "{{processName}}"
    }
   ]
  }
 ]
}