global: 
  smtp_smarthost: 'smtp.xxx.com:25'
  smtp_from: 'xxx'
  smtp_auth_username: 'xxx'
  smtp_auth_password: 'xxx'

route:
  group_by: ['alertname']
  group_interval: 10s
  # 重复发送通知的间隔时间
  repeat_interval: 5m
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
    - to: 'xxx'
      headers: { Subject: "[WARN] Alert Email"}
