global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 4s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['cita_monitor_server_alertmanager:9093']

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'host_exporter'
    static_configs:
    - targets: ['host_exporter_ip:port']

  - job_name: 'process_exporter'
    static_configs:
    - targets: ['process_exporter_ip:port']

  - job_name: 'rabbitmq_exporter'
    static_configs:
    - targets: ['rabbitmq_exporter_ip:port']

  - job_name: 'cita_exporter'
    static_configs:
    - targets: ['cita_exporter_ip:port']
