{
 "title": "CITA Node Info Dashboard",
 "description": "CITA Node Info Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(Node_Get_ServiceStatus,job)"
   },
   {
    "name": "node_id",
    "label": "NodeID",
    "query": "label_values(Node_Get_LastBlockNumber{job=~\"$job\"},NodeID) "
   },
   {
    "name": "node",
    "label": "节点",
    "query": "label_values(Node_Get_LastBlockNumber{job=~\"$job\",NodeID=~\"$node_id\"},instance)"
   },
   {
    "name": "port",
    "label": "端口",
    "query": "label_values(Node_Get_LastBlockNumber{job=~\"$job\",NodeID=~\"$node_id\"},instance)"
   },
   {
    "name": "ChainName",
    "label": "ChainName",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},ChainName)"
   },
   {
    "name": "Operator",
    "label": "Operator",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Operator)"
   },
   {
    "name": "TokenName",
    "label": "TokenName",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenName)"
   },
   {
    "name": "TokenSymbol",
    "label": "TokenSymbol",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenSymbol)"
   },
   {
    "name": "Version",
    "label": "Version",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Version)"
   },
   {
    "name": "FirstBlockNumberHash",
    "label": "FirstBlockNumberHash",
    "query": "label_values(Node_Get_FirstBlockNumberDetails{instance=~'$node:$port'},FirstBlockNumberHash)"
   },
   {
    "name": "LastBlockNumberHash",
    "label": "LastBlockNumberHash",
    "query": "label_values(Node_Get_LastBlockNumberDetails,LastBlockNumberHash) "
   },
   {
    "name": "node_dir",
    "label": "Node Dir",
    "query": "label_values(Node_Get_DirInfo_TotalFileSize{instance=~'$node:$port'},NodeDir) "
   },
   {
    "name": "ConsensusStatus",
    "label": "ConsensusStatus",
    "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},ConsensusStatus) "
   },
   {
    "name": "SoftVersion",
    "label": "SoftVersion",
    "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},SoftVersion) "
   },
   {
    "name": "HostPlatform",
    "label": "HostPlatform",
    "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},HostPlatform) "
   },
   {
    "name": "HostName",
    "label": "HostName",
    "query": "label_values(Node_Get_LastBlockNumberDetails{instance=~'$node:$port'},HostName) "
   },
   {
    "name": "NodeAddress",
    "label": "NodeAddress",
    "query": "label_values(Node_Get_LastBlockNumber{instance=~'$node:$port'},NodeAddress) "
   },
   {
    "name": "NodeIP",
    "label": "NodeIP",
    "query": "label_values(Node_Get_LastBlockNumber{instance=~'$node:$port'},NodeIP) "
   },
   {
    "name": "NodePort",
    "label": "NodePort",
    "query": "label_values(Node_Get_LastBlockNumber{instance=~'$node:$port'},NodePort) "
   }
  ]
 },
 "panels": [
  {
   "title": "Chain Meta Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "content": "<center>\n<h2>Chain Name</h2>\n<br><br>\n<h1>$ChainName</h1>\n</center>"
    },
    {
     "title": "Genesis Block Time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 10, "x": 4, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "Node_Get_FirstBlockNumberDetails{job=\"$job\",instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "title": "Network Run Time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - (Node_Get_FirstBlockNumberDetails{job=\"$job\",instance=\"$node:$port\"} / 1000)"
      }
     ]
    },
    {
     "title": "Protocol Version",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
     "content": "<center>\n<br>\n<h2>$Version</h2>\n</center>"
    },
    {
     "title": "Operator",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
     "content": "<center>\n<br>\n<h2>$Operator</h2>\n</center>"
    },
    {
     "title": "TokenSymbol",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
     "content": "<center>\n<br>\n<h2>$TokenSymbol</h2>\n</center>"
    },
    {
     "title": "Economic Model",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "Node_Get_ChainInfo{job=\"$job\",instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  { "title": "Chain Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Last Block Number of [ $ChainName ]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(Node_Get_LastBlockNumber{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Consensus Nodes of [ $ChainName ]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(Node_Get_ChainNodes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Block Number of [ $ChainName ]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Block Limit of [ $ChainName ]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "Node_Get_BlockQuotaLimit{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Quota Price of [ $ChainName ]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "Node_Get_QuotaPrice{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 11 },
   "content": "<center>\n<div align=\"left\">\n<h2>Node ID : <span>$node_id</span></h2>\n<h2>Node JSON-RPC : <span>$NodeIP:$NodePort</span></h2>\n</div>\n</center>"
  },
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Last Block Number",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last Block Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - (Node_Get_LastBlockNumberDetails{job=\"$job\",instance=\"$node:$port\"} / 1000)"
    }
   ]
  },
  {
   "title": "Last Block is Proposer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_CheckProposer{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last Block TX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last Block Interval",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 16 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_BlockDifference{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last [ 1h ] Avg Block Interval Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 16 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(Node_Get_BlockTimeDifference{job=\"$job\",instance=\"$node:$port\"}[1h])"
    }
   ]
  },
  {
   "title": "Block TX History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Block Interval",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Node_Get_BlockTimeDifference{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Last 1m TPS/s",
   "type": "singlestat",
   "description": "sum_over_time(Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$instance\"}[1m]) / 60",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(Node_Get_LastBlockNumberTransactions{job=\"$job\",instance=\"$node:$port\"}[1m]) / 60"
    }
   ]
  },
  {
   "title": "Quota Info",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_BlockQuotaLimit{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "Block Limit"
    },
    {
     "expr": "Node_Get_LastBlockNumberQuotaUsed{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "Quota Used"
    },
    {
     "expr": "Node_Get_LastBlockNumber{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "Block Number"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 39 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_DirInfo_TotalFileSize{job=\"$job\",instance=\"$node:$port\"} * 1024",
     "legendFormat": "Node Dir Size Used by [ node : $node_id ]"
    },
    {
     "expr": "Node_Get_DiskInfo_UsedSize{job=\"$job\",instance=\"$node:$port\"} - (Node_Get_DirInfo_TotalFileSize{job=\"$job\",instance=\"$node:$port\"} * 1024)",
     "legendFormat": "Other Used"
    },
    {
     "expr": "Node_Get_DiskInfo_FreeSize{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Node Dir Size Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 45 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "Node_Get_DirInfo_TotalFileSize{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}} - {{NodeDir}}"
    }
   ]
  },
  {
   "title": "NodeAddress",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 45 },
   "content": "<center>\n<br>\n<h1>$NodeAddress</h1>\n</center>"
  },
  {
   "title": "SoftVersion",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 48 },
   "content": "<center>\n<br>\n<h5>$SoftVersion</h5>\n</center>"
  },
  {
   "title": "HostName",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 48 },
   "content": "<center>\n<br>\n<h3>$HostName</h3>\n</center>"
  },
  {
   "title": "Node Type",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 51 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "$ConsensusStatus" }
   ]
  },
  {
   "title": "HostPlatform",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 51 },
   "content": "<center>\n<br><br>\n<h3>$HostPlatform</h3>\n</center>"
  },
  {
   "title": "Node Peers Number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 53 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_NodePeers{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  }
 ]
}