{
 "title": "CITA Node Info Dashboard",
 "description": "CITA Node Info Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(Node_Get_ServiceStatus,job)"
   },
   {
    "name": "node",
    "label": "节点",
    "query": "label_values(Node_Get_ServiceStatus{job=~'$job'},instance)"
   },
   {
    "name": "port",
    "label": "端口",
    "query": "label_values(Node_Get_ServiceStatus{job=~'$job',instance=~'$node.+'},instance)"
   },
   {
    "name": "ChainName",
    "label": "ChainName",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},ChainName)"
   },
   {
    "name": "Operator",
    "label": "Operator",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Operator)"
   },
   {
    "name": "TokenName",
    "label": "TokenName",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenName)"
   },
   {
    "name": "TokenSymbol",
    "label": "TokenSymbol",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenSymbol)"
   },
   {
    "name": "Version",
    "label": "Version",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Version)"
   },
   {
    "name": "FirstBlocknumberHash",
    "label": "FirstBlocknumberHash",
    "query": "label_values(Node_Get_FirstBlocknumberDetails{instance=~'$node:$port'},FirstBlocknumberHash)"
   },
   {
    "name": "LastBlocknumberHash",
    "label": "LastBlocknumberHash",
    "query": "label_values(Node_Get_LastBlocknumberDetails,LastBlocknumberHash) "
   },
   {
    "name": "node_id",
    "label": "NodeID",
    "query": "label_values(Node_Get_LastBlocknumber{instance=~\"$node:$port\"},NodeID) "
   },
   {
    "name": "node_dir",
    "label": "Node Dir",
    "query": "label_values(Node_Get_DirInfo_TotalFileSize{instance=~'$node:$port'},NodeDir) "
   },
   {
    "name": "ConsensusStatus",
    "label": "ConsensusStatus",
    "query": "label_values(Node_Get_LastBlocknumberDetails{instance=~'$node:$port'},ConsensusStatus) "
   },
   {
    "name": "SoftVersion",
    "label": "SoftVersion",
    "query": "label_values(Node_Get_LastBlocknumberDetails{instance=~'$node:$port'},SoftVersion) "
   },
   {
    "name": "HostPlatform",
    "label": "HostPlatform",
    "query": "label_values(Node_Get_LastBlocknumberDetails{instance=~'$node:$port'},HostPlatform) "
   },
   {
    "name": "HostName",
    "label": "HostName",
    "query": "label_values(Node_Get_LastBlocknumberDetails{instance=~'$node:$port'},HostName) "
   },
   {
    "name": "NodeAddress",
    "label": "NodeAddress",
    "query": "label_values(Node_Get_LastBlocknumber{instance=~'$node:$port'},NodeAddress) "
   },
   {
    "name": "NodeIP",
    "label": "NodeIP",
    "query": "label_values(Node_Get_LastBlocknumber{instance=~'$node:$port'},NodeIP) "
   },
   {
    "name": "NodePort",
    "label": "NodePort",
    "query": "label_values(Node_Get_LastBlocknumber{instance=~'$node:$port'},NodePort) "
   },
   {
    "name": "NodeDisk",
    "label": "NodeDisk",
    "query": "label_values(Node_Get_DirInfo_TotalFileSize{instance=~'$node:$port'},NodeDisk) "
   },
   { "name": "Interval", "label": "BlockInterval", "query": "1m,10m,30m,1h,6h,12h,1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "Chain Meta Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "content": "<center>\n<h2>Chain Name</h2>\n<br><br>\n<h1>$ChainName</h1>\n</center>"
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 10, "x": 4, "y": 1 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "Node_Get_FirstBlocknumberDetails{job=\"$job\",instance=\"$node:$port\"}"
      }
     ]
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - (Node_Get_FirstBlocknumberDetails{job=\"$job\",instance=\"$node:$port\"} / 1000)"
      }
     ]
    },
    {
     "title": "Version",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
     "content": "<center>\n<br>\n<h2>$Version</h2>\n</center>"
    },
    {
     "title": "Operator",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
     "content": "<center>\n<br>\n<h2>$Operator</h2>\n</center>"
    },
    {
     "title": "TokenSymbol",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
     "content": "<center>\n<br>\n<h2>$TokenSymbol</h2>\n</center>"
    },
    {
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "Node_Get_ChainInfo{job=\"$job\",instance=\"$node:$port\"}"
      }
     ]
    }
   ]
  },
  { "title": "Chain Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Last Block Number of [ $ChainName ]",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(Node_Get_LastBlocknumber{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Consensus Nodes of [ $ChainName ]",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(Node_Get_ChainNodes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Block Number of [ $ChainName ]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlocknumber{job=\"$job\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Node Info From $NodeIP:$NodePort | node id $node_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Last Block Number",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_LastBlocknumber{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last Block Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - (Node_Get_LastBlocknumberDetails{job=\"$job\",instance=\"$node:$port\"} / 1000)"
    }
   ]
  },
  {
   "title": "Last Block is Proposer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_CheckProposer{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlocknumber{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Last Block TX",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_LastBlocknumberTransactions{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Block TX History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlocknumberTransactions{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Last Block Interval",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 15 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_BlockDifference{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "Last [ $Interval ] Avg Block Interval Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 15 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(Node_Get_BlockTimeDifference{job=\"$job\",instance=\"$node:$port\"}[$Interval])"
    }
   ]
  },
  {
   "title": "Block Interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Node_Get_BlockTimeDifference{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}}"
    }
   ]
  },
  {
   "title": "Last 1m TPS/s",
   "type": "singlestat",
   "description": "sum_over_time(Node_Get_LastBlocknumberTransactions{job=\"$job\",instance=\"$instance\"}[1m]) / 60",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(Node_Get_LastBlocknumberTransactions{job=\"$job\",instance=\"$node:$port\"}[1m]) / 60"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 26 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(Node_Get_DirInfo_TotalFileSize{job=\"$job\",instance=\"$node:$port\"} * 1024)",
     "legendFormat": "use"
    },
    { "expr": "$NodeDisk", "legendFormat": "total" }
   ]
  },
  {
   "title": "Node Dir Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "Node_Get_DirInfo_TotalFileSize{job=\"$job\",instance=\"$node:$port\"}",
     "legendFormat": "{{NodeIP}}:{{NodePort}} - {{NodeDir}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "$ConsensusStatus" }
   ]
  },
  {
   "title": "NodeAddress",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 27 },
   "content": "<center>\n<br>\n<h1>$NodeAddress</h1>\n</center>"
  },
  {
   "title": "Node Peers Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_NodePeers{job=\"$job\",instance=\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "SoftVersion",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 30 },
   "content": "<center>\n<br>\n<h5>$SoftVersion</h5>\n</center>"
  },
  {
   "title": "HostName",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 30 },
   "content": "<center>\n<br>\n<h3>$HostName</h3>\n</center>"
  },
  {
   "title": "HostPlatform",
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 33 },
   "content": "<center>\n<br>\n<h3>$HostPlatform</h3>\n</center>"
  }
 ]
}