{
 "title": "CitaAgent Exporter Dashboard",
 "description": "CitaAgent Exporter Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(Node_Get_ServiceStatus,job)"
   },
   {
    "name": "node",
    "label": "节点",
    "query": "label_values(Node_Get_ServiceStatus{job=~'$job'},instance)"
   },
   {
    "name": "port",
    "label": "端口",
    "query": "label_values(Node_Get_ServiceStatus{job=~'$job',instance=~'$node.+'},instance)"
   },
   {
    "name": "ChainName",
    "label": "ChainName",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},ChainName)"
   },
   {
    "name": "Operator",
    "label": "Operator",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Operator)"
   },
   {
    "name": "TokenName",
    "label": "TokenName",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenName)"
   },
   {
    "name": "TokenSymbol",
    "label": "TokenSymbol",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},TokenSymbol)"
   },
   {
    "name": "Version",
    "label": "Version",
    "query": "label_values(Node_Get_ChainInfo{instance=~'$node:$port'},Version)"
   },
   {
    "name": "FirstBlocknumberHash",
    "label": "FirstBlocknumberHash",
    "query": "label_values(Node_Get_FirstBlocknumberDetails{instance=~'$node:$port'},FirstBlocknumberHash)"
   },
   {
    "name": "LastBlocknumberHash",
    "label": "LastBlocknumberHash",
    "query": "label_values(Node_Get_LastBlocknumberDetails,LastBlocknumberHash) "
   },
   {
    "name": "node_id",
    "label": "NodeID",
    "query": "label_values(Node_Get_LastBlocknumber{instance=~\"$node:$port\"},NodeID) "
   },
   {
    "name": "node_dir",
    "label": "Node Dir",
    "query": "label_values(Node_Get_DirInfo_TotalFileSize{instance=~'$node:$port'},NodeDir) "
   }
  ]
 },
 "panels": [
  {
   "title": "Agent Work Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "Node_Get_ServiceStatus{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  { "title": "Chain Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "First Block Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_FirstBlocknumberDetails{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Chain Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "Node_Get_ChainNodes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Chain Running Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 4 },
   "format": "clockms",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_FirstBlocknumberDetails{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Chain Info From Instance $node:$port",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "content": "# ChainName : $ChainName\n# Operator : $Operator\n# TokenName : $TokenName\n# TokenSymbol : $TokenSymbol\n# Version : $Version\n# FirstBlocknumberHash : $FirstBlocknumberHash"
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Last Block Number",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "Node_Get_LastBlocknumber{instance=~\"$node:$port\",job=~\"$job\"}\t"
    }
   ]
  },
  {
   "title": "Last Block Time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 16 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "Node_Get_LastBlocknumberDetails{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Node Peers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "Node_Get_NodePeers{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Node ID",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "$node_id" }
   ]
  },
  {
   "title": "目录 [ $node_dir ]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "Node_Get_DirInfo_DirNumber{NodeDir=\"/github/cita_secp256k1_sha3/monitor_chain_02/0\"}",
     "legendFormat": "目录文件夹数量"
    },
    {
     "expr": "Node_Get_DirInfo_FilesNumber{NodeDir=\"/github/cita_secp256k1_sha3/monitor_chain_02/0\"}",
     "legendFormat": "目录文件数量"
    },
    {
     "expr": "Node_Get_DirInfo_TotalFileSize{NodeDir=\"/github/cita_secp256k1_sha3/monitor_chain_02/0\"}",
     "legendFormat": "目录使用总量"
    }
   ]
  }
 ]
}