{
 "title": "Node Exporter 监控展示看板",
 "description": "Node Exporter 监控展示看板",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(node_exporter_build_info, job)"
   },
   {
    "name": "name",
    "label": "主机名",
    "query": "label_values(node_uname_info{job=~'$job'},nodename)"
   },
   {
    "name": "node",
    "label": "节点",
    "query": "label_values(node_uname_info{nodename='$name'},instance)"
   },
   {
    "name": "port",
    "label": "端口",
    "query": "label_values(node_uname_info{nodename='$name'},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node:$port',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   }
  ]
 },
 "panels": [
  { "title": "$node:$port", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "系统运行时间",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU使用率（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node:$port\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node:$port\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node:$port\"} / (node_memory_MemTotal_bytes{instance=~\"$node:$port\"})))* 100"
    }
   ]
  },
  {
   "title": "当前打开的文件描述符",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node:$port\"}"
    }
   ]
  },
  {
   "title": "根分区使用率",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node:$port\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "最大分区($maxmount)使用率",
   "type": "singlestat",
   "description": "通过变量maxmount获取最大的分区。",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node:$port\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node:$port\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node:$port\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "磁盘总空间",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {instance=~\"$node:$port\",fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "各分区可用空间",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$node:$port',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node:$port',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node:$port',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node:$port',device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "TCP 连接情况",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node:$port'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node:$port'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node:$port'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node:$port'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node:$port'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node:$port'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  },
  {
   "title": "硬件温度",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node:$port\"}",
     "legendFormat": "{{chip}} {{sensor}}"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\"} - node_memory_MemAvailable_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "内存_Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "内存_Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "内存_Cached"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node:$port\"}",
     "legendFormat": "可用"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\"} - (node_memory_Cached_bytes{instance=~\"$node:$port\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\"} + node_memory_MemFree_bytes{instance=~\"$node:$port\"})"
    }
   ]
  }
 ]
}