{
 "title": "RabbitMQ Dashboard",
 "description": "RabbitMQ Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "节点",
    "query": "label_values(up{job=~'rabbitmq_exporter'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "RabbitMQ Server",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_up{instance=~'$node.+'}"
    }
   ]
  },
  {
   "title": "Node up Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_running{instance=~'$node.+'}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_exchangesTotal{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:exchanges"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_channelsTotal{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:channels"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_consumersTotal{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:consumers"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connectionsTotal{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:connections"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queuesTotal{instance=~'$node.+'}",
     "legendFormat": "{{instance}}:queues"
    }
   ]
  },
  {
   "title": "Messages/host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_ready{instance=~'$node.+'})",
     "legendFormat": "{{vhost}}:ready"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_published_total{instance=~'$node.+'})",
     "legendFormat": "{{vhost}}:published"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_delivered_total{instance=~'$node.+'})",
     "legendFormat": "{{vhost}}:delivered"
    },
    {
     "expr": "sum by (vhost)(rabbitmq_queue_messages_unacknowledged{instance=~'$node.+'})",
     "legendFormat": "{{vhost}}:unack"
    }
   ]
  },
  {
   "title": "Messages / Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{instance=~'$node.+'}",
     "legendFormat": "{{queue}}:{{durable}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{instance=~'$node.+'}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{instance=~'$node.+'}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "FIle descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_fd_used{instance=~'$node.+'}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_fd_total{instance=~'$node.+'}",
     "legendFormat": "{{node}}:total"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_sockets_used{instance=~'$node.+'}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_sockets_total{instance=~'$node.+'}",
     "legendFormat": "{{node}}:total"
    }
   ]
  }
 ]
}