{
 "title": "Sum Exporter Dashboard",
 "description": "Sum Exporter Dashboard",
 "tags": [
  "Prometheus",
  "Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(up,job)" },
   {
    "name": "Chain",
    "label": "Chain(创世块 Hash)",
    "query": "label_values(Node_Get_LastBlocknumber,FirstBlocknumberHash)"
   }
  ]
 },
 "panels": [
  {
   "title": "面板列表",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "type": "dashlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 } }
   ]
  },
  { "title": "区块产出预览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "( $job ) Running Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "cita-cli exporter 运行状态" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU use percent by 5min avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 2 },
   "yaxes": [
    { "format": "percent", "label": "5分钟的 CPU 平均利用率" }
   ],
   "targets": [
    {
     "expr": "100 - (avg without(cpu)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Block Number From Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "Node_Get_LastBlocknumber{FirstBlocknumberHash=~'$Chain'}"
    }
   ]
  },
  {
   "title": "Last Block Number From Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Node_Get_LastBlocknumber{FirstBlocknumberHash=~'$Chain'}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}