#!/bin/sh
#
. /etc/init.d/functions

WORK_DIR="/opt/cita-agent"
EXEC="/usr/bin/python3 $WORK_DIR/cita-agent.py"

PIDFILE=$WORK_DIR/cita-agentd.pid

start() {
	if [ -f $PIDFILE ]
	then
			echo "$PIDFILE exists, process is already running or crashed"
	else
			echo "Starting cita Agent..."
			nohup $EXEC >/dev/null 2>&1 &
	fi
}

stop() {
	if [ ! -f $PIDFILE ]
	then
			echo "$PIDFILE does not exist, process is not running"
	else
			PID=$(cat $PIDFILE)
			echo "Stopping ..."
			kill -9 $PID
			rm -rf $WORK_DIR/cita-agentd.pid
			while [ -x /proc/${PID} ]
			do
				echo "Waiting for cita Agent to shutdown ..."
				sleep 1
			done
			echo "cita agent stopped"
	fi
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
        ;;
    status)
	if [ -f $PIDFILE ]
	then
		echo "cita agent is running....."
	else
		echo "cita agent is stopped"
	fi
	;;
    restart)
	restart
	;;
    *)
        echo "service status or stop or start"
        ;;
esac